name: Continuous Integration NPM

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - master
      - develop
      - staging

env:
  MAINNET_PRC_ENDPOINT: ${{ secrets.MAINNET_RPC_ENDPOINT }}
  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  working_dir: ./ts-client

jobs:
  changed_files_ts:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            ts-client

  ts-test:
    needs: changed_files_ts
    if: needs.changed_files_ts.outputs.program == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 9.1.4
      - name: Install dependencies
        working-directory: ${{ env.working_dir }}
        run: pnpm install
      - name: create env file
        working-directory: ${{ env.working_dir }}
        run: |
          touch .env
          echo MAINNET_RPC_ENDPOINT=${{ env.MAINNET_PRC_ENDPOINT }} >> .env
          echo WALLET_PRIVATE_KEY=${{ env.WALLET_PRIVATE_KEY }} >> .env
      - name: Run tests
        working-directory: ${{ env.working_dir }}
        run: pnpm run test
